function getById(id){
    return document.getElementById(id);
}

let hotlineP = getById("hotline");
let hotlineList = [
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "National Emergency Service",
        subtitle: "National Emergency",
        number: "999",
        category: "All",
    },
    {
        icon: "police",
        bgColor: "bg-[#dfefff]",
        title: "Police Helpline Service",
        subtitle: "Police",
        number: "999",
        category: "Police",
    },
    {
        icon: "fire-service",
        bgColor: "bg-[#ffe3e2]",
        title: "Fire Service Number",
        subtitle: "Fire Service",
        number: "999",
        category: "Fire",
    },
    {
        icon: "ambulance",
        bgColor: "bg-[#ffe3e2]",
        title: "Ambulance Service",
        subtitle: "Ambulance",
        number: "1994-999999",
        category: "Health",
    },
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "Women & Child Helpline",
        subtitle: "Women & Child Helpline",
        number: "109",
        category: "Help",
    },
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "Anti-Corruption Helpline",
        subtitle: "Anti-Corruption",
        number: "106",
        category: "Govt.",
    },
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "Electricity Helpline",
        subtitle: "Electricity Outage",
        number: "16216",
        category: "Electricity",
    },
    {
        icon: "brac",
        bgColor: "bg-pink-100",
        title: "Brac Helpline",
        subtitle: "Brac",
        number: "16445",
        category: "NGO",
    },
    {
        icon: "Bangladesh-Railway",
        bgColor: "bg-amber-100",
        title: "Bangladesh Railway Helpline ",
        subtitle: "Bangladesh Railway",
        number: "163",
        category: "Travel",
    },
];

// here Dynamic card Content is generated by for loop

for(let hotline of hotlineList){
    hotlineP.innerHTML += `
               <div id="history" class="bg-base-100 card w-full shadow-sm">
            <div class="p-4">
               <div class="flex justify-between items-center">
                <img src="./assets/${hotline.icon}.png" alt="hotline.title"
                class=" bg-[#ffe3e2] size-14 p-3 mb-2 rounded-2xl">
                <i class="fa-regular fa-heart text-xl cursor-pointer 
                onclick=" " "></i>

               </div>
               <h3 class="text-2xl font-bold font-sans text-[#111]">${hotline.title}</h3>
               <p class="text-[18px] text-[#5c5c5c] font-roboto">${hotline.subtitle}</p>
               <h2 class="text-2xl font-bold font-sans text-[#111]">${hotline.number}</h2>
               <span class="bg-[#f2f2f2] py-1.5 px-5 rounded-full inline-block my-2 text-[#5c5c5c]"> ${hotline.category}</span>
                  
                 <div class="grid grid-cols-2 gap-2">

                  <button type="button" onclick="copyNumber('${hotline.number}')" class="border border-[#d4d6d5] rounded-lg p-2 cursor-pointer
                   text-[#5c5c5c] duration-350 hover:border-black hover:bg-black hover:text-white">
                   <i class="fa-regular fa-clone"></i> Copy</button>

                    <button type="button" onclick="callEmergency(
                    '${hotline.title}', '${hotline.number}');" class="bg-[#00a63e] rounded-lg p-2 cursor-pointer text-white
                     duration-350 hover:bg-[#d4d6d4]"><i class="fa-solid fa-phone"></i> Call</button>

                  </div>

              </div>
           </div>
    
    `;
}

