function getById(id){
    return document.getElementById(id);
}

let hotlineP = getById("hotline");
let hotlineList = [
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "National Emergency Service",
        subtitle: "National Emergency",
        number: "999",
        category: "All",
    },
    {
        icon: "police",
        bgColor: "bg-[#dfefff]",
        title: "Police Helpline Service",
        subtitle: "Police",
        number: "999",
        category: "Police",
    },
    {
        icon: "fire-service",
        bgColor: "bg-[#ffe3e2]",
        title: "Fire Service Number",
        subtitle: "Fire Service",
        number: "999",
        category: "Fire",
    },
    {
        icon: "ambulance",
        bgColor: "bg-[#ffe3e2]",
        title: "Ambulance Service",
        subtitle: "Ambulance",
        number: "1994-999999",
        category: "Health",
    },
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "Women & Child Helpline",
        subtitle: "Women & Child Helpline",
        number: "109",
        category: "Help",
    },
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "Anti-Corruption Helpline",
        subtitle: "Anti-Corruption",
        number: "106",
        category: "Govt.",
    },
    {
        icon: "emergency",
        bgColor: "bg-[#ffe3e2]",
        title: "Electricity Helpline",
        subtitle: "Electricity Outage",
        number: "16216",
        category: "Electricity",
    },
    {
        icon: "brac",
        bgColor: "bg-[#ffe3e2]",
        title: "Brac Helpline",
        subtitle: "Brac",
        number: "16445",
        category: "NGO",
    },
    {
        icon: "Bangladesh-Railway",
        bgColor: "bg-[#fef3c7]",
        title: "Bangladesh Railway Helpline ",
        subtitle: "Bangladesh Railway",
        number: "163",
        category: "Travel",
    },
];



//dynamic heart count
let heartCount = 0;
let heartCountP = getById("heart-count");

function heartCounter(){
    heartCount++;
    heartCountP.innerText = heartCount;
}

// copy button functionality
let copyCount = 0;
let copyCountP = getById("copy-count");

function copyNumber(number){
    copyCount++;
    copyCountP.innerHTML = copyCount;
    navigator.clipboard.writeText(number);
    alert(`Number Copied: ${number}`);
}

// here Dynamic card Content is generated by for loop

for(let hotline of hotlineList){

    hotlineP.innerHTML += `
	
        <div class="card w-full bg-base-100 shadow-sm">
            <div class="p-4">
                <div class="flex justify-between items-center">
                    <img src="assets/${hotline.icon}.png" alt="${hotline.title}" 
					class="${hotline.bgColor} size-14 p-3 rounded-2xl mb-2">
                    <i class="fa-regular fa-heart text-xl cursor-pointer" onclick="heartCounter()"></i>
                </div>
				
                <h4 class="text-2xl font-hind-madurai font-bold text-[#111]">${hotline.title}</h4>
                <p class="text-[18px] text-[#5c5c5c] font-roboto">${hotline.subtitle}</p>
                <h3 class="text-2xl font-bold font-sans text-[#111]">${hotline.number}</h3>
                <span class="bg-[#f2f2f2] py-1.5 px-5 rounded-full inline-block my-2 text-[#5c5c5c]">${hotline.category}</span>
				
                <div class="grid grid-cols-2 gap-2">
                    <button type="button" onclick="copyNumber('${hotline.number}')" class="border border-[#d4d6d5] rounded-lg p-2 cursor-pointer 
					text-[#5c5c5c] duration-300 hover:border-black hover:bg-black hover:text-white"><i class="fa-regular fa-clone"></i> Copy</button>
					
                    <button type="button" onclick="callEmergency(
                    '${hotline.title}', '${hotline.number}');" class="bg-[#00a63e] rounded-lg p-2 cursor-pointer text-white 
					duration-300 hover:bg-[#d4d6d6] hover:text-white"><i class="fa-solid fa-phone"></i> Call</button>
                </div>
				
            </div>
        </div>
    `;
}



        // call button functionality
let coinCount = 100;
let coinCountP = getById("coin-count");

function callEmergency(hotlineName , hotlineNumber){
    if(coinCount < 20){
        alert("⚠️ You don't have sufficient coin! To make call, you need at least 20 coins.");
        return;
    }

    coinCount -= 20;
    coinCountP.innerText = coinCount;
    alert(`📞 Calling ${hotlineName} ${hotlineNumber} ... `);
    createHistory(hotlineName , hotlineNumber);
}

//Dynamic Call history with history clear functionality

function createHistory(hotlineName , hotlineNumber){
let callHistoryP = getById("call-history");
    callHistoryP.innerHTML += `
   
       <div class="bg-neutral-50 p-4 rounded-2xl flex justify-between items-center">
            <div>
                <p class="text-[18px] font-semibold text-[#111]">${hotlineName}</p>
                <p class="font-hind-madurai text-[18px] text-[#5c5c5c]">${hotlineNumber.toString()}</p>
            </div>

            <div>
                <p class="font-hind-madurai text-[18px] text-right text-[#383838]">
                 ${new Date().toLocaleTimeString()}
                </p>
            </div>
       </div>
    `; 
}

     // history clear function
let clearHistoryBtn = getById("clear-btn")

function clearHistory(){
    let clearHistoryP = getById("call-history");
    clearHistoryP.innerHTML = "";
}

clearHistoryBtn.addEventListener("click", clearHistory);

